import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { saveAs } from 'file-saver';

export const exportToCSV = (transactions, currency) => {
    if (!transactions || transactions.length === 0) {
        console.warn('No transactions to export');
        return;
    }

    try {
        // Define headers
        const headers = ['Date', 'Type', 'Category', 'Amount', 'Note'];

        // Convert data to CSV format
        const csvContent = [
            headers.join(','),
            ...transactions.map(t => {
                const row = [
                    t.date,
                    t.type,
                    t.category,
                    t.amount,
                    `"${(t.note || '').replace(/"/g, '""')}"` // Escape quotes in notes
                ];
                return row.join(',');
            })
        ].join('\n');

        // Create blob with BOM for Excel compatibility
        const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' });

        // Use file-saver to save the file
        saveAs(blob, `kore_transactions_${new Date().toISOString().split('T')[0]}.csv`);

    } catch (error) {
        console.error('CSV Export Error:', error);
        alert('Failed to export CSV. Please check console for details.');
    }
};

export const exportToPDF = (transactions, currency, user) => {
    if (!transactions || transactions.length === 0) {
        console.warn('No transactions to export');
        return;
    }

    try {
        const doc = new jsPDF();
        const themeColor = [79, 70, 229]; // Indigo-600

        // -- Header --
        doc.setFontSize(20);
        doc.setTextColor(...themeColor);
        doc.text('Kore', 14, 22);

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('Financial Report', 14, 28);

        // User Info & Date
        doc.setFontSize(10);
        doc.setTextColor(50);
        const dateStr = new Date().toLocaleDateString();
        doc.text(`Generated on: ${dateStr}`, 140, 22);
        if (user?.name) {
            doc.text(`User: ${user.name}`, 140, 28);
        }

        // -- Summary --
        const income = transactions.filter(t => t.amount > 0).reduce((acc, t) => acc + t.amount, 0);
        const expense = transactions.filter(t => t.amount < 0).reduce((acc, t) => acc + Math.abs(t.amount), 0);
        const balance = income - expense;

        doc.setFillColor(245, 247, 255);
        doc.roundedRect(14, 35, 182, 25, 3, 3, 'F');

        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text('Total Income', 25, 45);
        doc.text('Total Expense', 85, 45);
        doc.text('Net Balance', 145, 45);

        doc.setFontSize(12);
        doc.setTextColor(16, 185, 129); // Emerald
        doc.text(`${currency.symbol}${income.toFixed(2)}`, 25, 53);

        doc.setTextColor(239, 68, 68); // Rose
        doc.text(`${currency.symbol}${expense.toFixed(2)}`, 85, 53);

        doc.setTextColor(themeColor[0], themeColor[1], themeColor[2]);
        doc.text(`${currency.symbol}${balance.toFixed(2)}`, 145, 53);

        // -- Table --
        const tableColumn = ["Date", "Type", "Category", "Amount", "Note"];
        const tableRows = [];

        transactions.forEach(t => {
            const transactionData = [
                t.date,
                t.type.charAt(0).toUpperCase() + t.type.slice(1),
                t.category,
                `${currency.symbol}${Math.abs(t.amount).toFixed(2)}`,
                t.note || '-'
            ];
            tableRows.push(transactionData);
        });

        // Use autoTable as a function passing the doc instance
        autoTable(doc, {
            startY: 70,
            head: [tableColumn],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: themeColor, textColor: 255 },
            alternateRowStyles: { fillColor: [249, 250, 251] },
            styles: { fontSize: 9, cellPadding: 3 },
        });

        // -- Footer --
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(`Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
            doc.text('Generated by Kore', 14, 290);
        }

        // Save using file-saver for consistency
        const pdfBlob = doc.output('blob');
        saveAs(pdfBlob, `kore_report_${new Date().toISOString().split('T')[0]}.pdf`);

    } catch (error) {
        console.error('PDF Export Error:', error);
        alert('Failed to export PDF. Please check console for details.');
    }
};
